config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :fincas
  end

  root 'static_pages#index'
  get 'contacto' => 'static_pages#contacto'
  get 'quienes_somos' => 'static_pages#quienes_somos'
  get 'fincas_home' => 'static_pages#fincas'
  get 'vinos_home' => 'static_pages#vinos'
  get 'vinos_single' => 'static_pages#vinos_single'
  get 'turismo_y_eventos' => 'static_pages#eventos'
  get 'admin' => 'admin#index'
  post 'contact_mail' => 'static_pages#contacto_mail'

  get '/fincas/:uid' => 'static_pages#finca_single'
  get '/change_locale/:locale' => 'static_pages#change_locale'
  get '/:category_title' => 'static_pages#vinos_single'

  devise_for :users, controllers: {sessions: "sessions"}

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :wines
  has_attached_file :image, styles: { medium: "500"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  translates :description

end

app/models/finca.rb
class Finca < ActiveRecord::Base
  has_many :finca_imgs
  translates :name, :description
  before_save { |t| t.uid = t.name.downcase.dasherize.tr(' ','-') }

end

app/models/finca_img.rb
class FincaImg < ActiveRecord::Base
  belongs_to :finca

  has_attached_file :image, styles: { original: "1280", medium: "600"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable


end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :category

  has_attached_file :image, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  translates :description_terroir, :description_taste, :recommendation
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  skip_before_action :restrict_access, only: [:index]
  before_action :authenticate_user!

  def index
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :restrict_access
  before_action :set_locale

  def set_locale
    if cookies[:vistandes_locale] && I18n.available_locales.include?(cookies[:vistandes_locale].to_sym)
      lang = cookies[:vistandes_locale].to_sym
    else
      lang = I18n.default_locale
      cookies.permanent[:vistandes_locale] = lang
    end
    I18n.locale = lang
  end

  def restrict_access
    redirect_to root_url unless user_signed_in?
  end
end

app/controllers/fincas_controller.rb
class FincasController < ApplicationController
  layout "admin"
  skip_before_action :restrict_access
  before_action :set_finca, only: [:show, :edit, :update, :destroy]

  # GET /fincas
  # GET /fincas.json
  def index
    @fincas = Finca.all
  end

  # GET /fincas/1
  # GET /fincas/1.json
  def show
  end

  # GET /fincas/new
  def new
    @finca = Finca.new
  end

  # GET /fincas/1/edit
  def edit
  end

  # POST /fincas
  # POST /fincas.json
  def create
    @finca = Finca.new(finca_params)

    respond_to do |format|
      if @finca.save
        format.html { redirect_to @finca, notice: 'Finca was successfully created.' }
        format.json { render :show, status: :created, location: @finca }
      else
        format.html { render :new }
        format.json { render json: @finca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fincas/1
  # PATCH/PUT /fincas/1.json
  def update
    respond_to do |format|
      if @finca.update(finca_params)
        format.html { redirect_to @finca, notice: 'Finca was successfully updated.' }
        format.json { render :show, status: :ok, location: @finca }
      else
        format.html { render :edit }
        format.json { render json: @finca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fincas/1
  # DELETE /fincas/1.json
  def destroy
    @finca.destroy
    respond_to do |format|
      format.html { redirect_to fincas_url, notice: 'Finca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finca
      @finca = Finca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finca_params
      params.require(:finca).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout "admin"
  skip_before_action :restrict_access
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :restrict_access
  before_action :set_category
  before_action :set_fincas

  def index

  end

  def contacto

  end

  def quienes_somos

  end

  def fincas
    @fincas = Finca.all.includes(:finca_imgs)
  end

  def finca_single
    @finca = Finca.find_by(uid: params[:uid])
    redirect_to root_url if @finca.blank?
  end

  def vinos
    @categories = Category.all
  end

  def vinos_single
    @wines = Category.includes(:wines).find_by(title: params[:category_title])
    redirect_to root_url if @wines.blank?
  end

  def eventos
  end

  def contacto_mail
    respond_to do |format|
      ContactEmail.contacto(mail_params).deliver_now
      format.html { redirect_to contacto_url, notice: 'Gracias por enviarnos su mensaje.' }
    end
  end

  def change_locale
    lang = params[:locale].to_sym
    lang = I18n.default_locale unless I18n.available_locales.include?(lang)
    cookies.permanent[:vistandes_locale] = lang
    redirect_to request.referer || root_url
  end

  private
    def set_category
      @categories = Category.select(:title)
    end

    def set_fincas
      @fincas_head = Finca.all
    end

    def mail_params
      params.require(:contact_form).permit(:nombre, :email, :asunto, :mensaje)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fincas_helper.rb
module FincasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/index.html.slim
= link_to('Fincas', fincas_url)

app/views/contact_email/contacto.html.erb
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><%= @asunto %></title>

</head>

<body style="height: 100%;margin: 0;padding: 0;width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FAFAFA;">
	<center>
		<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 0;width: 100%;background-color: #FAFAFA;">
			<tr>
				<td align="center" valign="top" id="bodyCell" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 10px;width: 100%;border-top: 0;">
					<!-- BEGIN TEMPLATE // -->
					<!--[if gte mso 9]>
						<table align="center" border="0" cellspacing="0" cellpadding="0" width="600" style="width:600px;">
						<tr>
						<td align="center" valign="top" width="600" style="width:600px;">
						<![endif]-->
					<table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: 0;max-width: 600px !important;">
						<tr>
							<td valign="top" id="templatePreheader" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FAFAFA;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;"></td>
						</tr>
						<tr>
							<td valign="top" id="templateHeader" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFFFFF;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 0;"></td>
						</tr>
						<tr>
							<td valign="top" id="templateBody" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFFFFF;border-top: 0;border-bottom: 2px solid #EAEAEA;padding-top: 0;padding-bottom: 9px;">
								<table class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" border="0" cellpadding="0" cellspacing="0">
									<tbody class="mcnTextBlockOuter">
										<tr>
											<td class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" valign="top">
												<!--[if mso]>
				<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">
				<tr>
				<![endif]-->

												<!--[if mso]>
				<td valign="top" width="600" style="width:600px;">
				<![endif]-->
												<table style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnTextContentContainer" align="left" width="100%" border="0" cellpadding="0"
														cellspacing="0">
													<tbody>
														<tr>

															<td class="mcnTextContent" style="padding-top: 0;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;"
																	valign="top">

																<h1 style="display: block;margin: 0;padding: 0;color: #202020;font-family: Helvetica;font-size: 26px;font-style: normal;font-weight: bold;line-height: 125%;letter-spacing: normal;text-align: left;">Contacto</h1>

																<p style="margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;"> <%= @nombre %> le ha enviado un mensaje desde la web:</p>

																<p style="margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;"><%= @mensaje %></p>

																<p style="margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;">Puedes responder al siguiente email. <a class="mc-template-link" href="mailto:<%=@email%>" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #2BAADF;font-weight: normal;text-decoration: underline;"><%= @email %></a></p>

                                <p style="margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;">Saludos</p>
															</td>
														</tr>
													</tbody>
												</table>
												<!--[if mso]>
				</td>
				<![endif]-->

												<!--[if mso]>
				</tr>
				</table>
				<![endif]-->
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td valign="top" id="templateFooter" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FAFAFA;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;"></td>
						</tr>
					</table>
					<!--[if gte mso 9]>
						</td>
						</tr>
						</table>
						<![endif]-->
					<!-- // END TEMPLATE -->
				</td>
			</tr>
		</table>
	</center>
</body>

app/views/fincas/_form.html.slim
= simple_form_for(@finca) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, required: true
    = f.input :description, required: true

  .form-actions
    = f.button :submit

app/views/fincas/edit.html.slim
h1 Editing finca

== render 'form'

= link_to 'Show', @finca
'|
= link_to 'Back', fincas_path

app/views/fincas/index.html.slim
h1 Listing fincas

table
  thead
    tr
      th Name
      th Description
      th colspan="3"

  tbody
    - @fincas.each do |finca|
      tr
        td = finca.name
        td = finca.description
        td = link_to 'Show', finca
        td = link_to 'Edit', edit_finca_path(finca)
        td = link_to 'Destroy', finca, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Finca', new_finca_path

app/views/fincas/new.html.slim
h1 New finca

== render 'form'

= link_to 'Back', fincas_path

app/views/fincas/show.html.slim
p#notice = notice


= link_to 'Edit', edit_finca_path(@finca)
'|
= link_to 'Back', fincas_path

app/views/layouts/_header.html.slim
header#header.no-sticky
  #header-wrap
    #logo.nobottomborder
      a.standard-logo href=root_path data-dark-logo="#{asset_path('logo.png')}"
        img src="#{asset_path('logo.png')}" alt="Vistandes Logo"
      a.retina-logo href=root_path data-dark-logo="#{asset_path('logo.png')}"
        img src="#{asset_path('logo.png')}" alt="Vistandes Logo"
    .container.clearfix
      #primary-menu-trigger
        i.icon-reorder
      nav#primary-menu
        ul
          li
            a href=root_url
              div == t('inicio')
          li
            = link_to content_tag(:div, t('quienes_somos.titulo').upcase), quienes_somos_url
          li.subclass_fincas
            a href=fincas_home_url
              = content_tag(:div, t('fincas.titulo').upcase)
            ul
              -@fincas_head.each do |finca|
                li
                  a href="#{root_url}fincas/#{finca.uid}"
                    div = finca.name
          li.subclass_wines
            a href=vinos_home_url
              div == t('vinos.titulo').upcase 
            ul
              - @categories.each do |category|
                li
                  a href="#{root_url + category.title}"
                    div = category.title
          li
            a href=turismo_y_eventos_url
              div == t('turismo.titulo').upcase 
          li
            a href=contacto_url
              div == t('contacto.titulo').upcase 
          li.mobile
            .lang
              a href="#{root_url}change_locale/en"
                img src="#{asset_path('english.png')}" alt="Language Flag" title="View this site in english"
              a href="#{root_url}change_locale/es"
                img src="#{asset_path('spanish.png')}" alt="Language Flag" title="Ver en español"
            
      div style="display:flex"
        .clearfix.visible-md.visible-lg style="margin: auto"
          a.social-icon.si-small.si-borderless.si-facebook target="_blank" href="https://www.facebook.com/Vistandes/?ref=br_rs&fref=nf" 
            i.icon-facebook
            i.icon-facebook

          a.social-icon.si-small.si-borderless.si-gplus target="_blank" href="https://www.google.com.ar/maps/place/Vistandes/@-33.024256,-68.758978,15z/data=!4m5!3m4!1s0x0:0xd6bbd8c3d6f103bc!8m2!3d-33.024256!4d-68.758978"
            i.icon-map
            i.icon-map

          a.social-icon.si-small.si-borderless.si-twitter target="_blank" href="mailto:info@vistandes.com?Subject=Contacto"
            i.icon-email2
            i.icon-email2
          
          br/
          br/
          .lang
            a href="#{root_url}change_locale/en"
              img src="#{asset_path('english.png')}" alt="Language Flag" title="View this site in english"
            a href="#{root_url}change_locale/es"
              img src="#{asset_path('spanish.png')}" alt="Language Flag" title="Ver en español"
          

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)

    div id="msg_alert" data-notify-msg="#{msg}" data-notify-type="#{name.to_s == 'notice' ? 'success' : 'error'}" data-notify-close="true"

    javascript:
      $(function(){
        function loadAlert(element){
          toastr.clear();

          var notifyElement = $(element);
          var notifyPosition = notifyElement.attr('data-notify-position');
          var notifyType = notifyElement.attr('data-notify-type');
          var notifyMsg = notifyElement.attr('data-notify-msg');
          var notifyCloseButton = notifyElement.attr('data-notify-close');

          if( !notifyPosition ){
            notifyPosition = 'toast-top-right';
          }else{
            notifyPosition = 'toast-' + notifyElement.attr('data-notify-position');
          }
          if( !notifyMsg ){
            notifyMsg = 'Please set a message!';
          }
          if( notifyCloseButton == 'true' ){
            notifyCloseButton = true;
          }else{
            notifyCloseButton = false;
          }
          toastr.options.positionClass = notifyPosition;
          toastr.options.closeButton = notifyCloseButton;
          toastr.options.closeHtml = '<button type="button" class="close">×</button>';
          if( notifyType == 'warning' ) {
            toastr.warning(notifyMsg);
          } else if( notifyType == 'error' ) {
            toastr.error(notifyMsg);
          } else if( notifyType == 'success' ) {
            toastr.success(notifyMsg);
          } else {
            toastr.info(notifyMsg);
          }
          return false;
        }
        loadAlert($('#msg_alert'));
      });
- flash[:error] = flash[:errors] = flash[:notice] = nil

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Vistandes | Admin
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag 'jquery'
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic"  	
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Quicksand' 
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Tangerine'
    
  body.stretched.side-header
    .clearfix.container
      = yield 
    
    = javascript_include_tag 'functions'
  

app/views/layouts/application.html.slim
doctype html
html
  head
    title Vistandes
    meta http-equiv="content-type" content="text/html; charset=utf-8" /
    meta name="author" content="Gonzalo Grassi" /
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /
    = favicon_link_tag 'favicon.png'
    = csrf_meta_tags
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic"  	
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Quicksand' 
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Tangerine'
    
    = javascript_include_tag 'jquery'
    = javascript_include_tag 'plugins'
    = javascript_include_tag 'bx-slider'
    = javascript_include_tag 'toastr'
    
  body.stretched.side-header
    = render 'layouts/messages'
    #wrapper.clearfix
      = render 'layouts/header'
      = yield 
    
    = javascript_include_tag 'functions'
  
    javascript:
      $(function(){
        
        var current_page = "#{yield(:current_page)}".toUpperCase().trim();
        var current_category = "#{yield(:current_category)}";
        var current_finca = "#{yield(:current_finca)}"
        
        switch(current_page) {
          case "VINOS_SINGLE":
            $('.subclass_wines>ul').css('display', 'block');
            $('#primary-menu .subclass_wines div').each(function(){
              if($(this).html().trim() === current_category){
                $(this).parent().parent().addClass('current');
                return false;
              }
            });
            break;
          case "FINCA_SINGLE":
            $('.subclass_fincas>ul').css('display', 'block');
            $('#primary-menu .subclass_fincas div').each(function(){
              if($(this).html().trim() === current_finca){
                $(this).parent().parent().addClass('current');
                return false;
              }
            });
            break;
          default:
            $('#primary-menu div').each(function(){
              var st = $(this).html().replace('&nbsp;' , " ").toUpperCase().trim();
              if(st === current_page){
                $(this).parent().parent().addClass('current');
                return false;
              }
            });
        }
        
        function getText($node){
          return $node.toString();
        }        
      });
      
  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-79231601-1', 'auto');
    ga('send', 'pageview');

app/views/static_pages/contacto.html.slim
- provide(:current_page, t('contacto.titulo'))
section#content
    .content-wrap
        .container.clearfix
            .col_half
                .fancy-title.title-dotted-border
                    h3 = t('contacto.subtitulo')
                #contact-form-result data-notify-type="success" data-notify-msg="<i class=icon-ok-sign></i> Message Sent Successfully!"
                = simple_form_for :contact_form, url: contact_mail_url, method: 'POST', html: {:id => "template-contact", :class => "form nobottommargin"} do |f| 
                    .form-process
                    .col_half
                        label for="nombre" 
                          = t('contacto.nombre')
                          small *
                        = f.input_field :nombre, class: 'sm-form-control required', required: true, maxlength: '50', id: 'nombre'
                    .col_half.col_last
                        label for="email" 
                          |Email 
                          small *
                        = f.input_field :email, class: 'required email sm-form-control', required: true, maxlength: '255', id: 'email'
                    .clear
                    .col_full
                        label for="asunto"
                          = t('contacto.asunto')
                          small *
                        = f.input_field :asunto, class:'required sm-form-control', required: true, maxlength: '50', id: 'asunto'
                    .clear
                    .col_full
                        label for="template-contactform-message" 
                          = t('contacto.mensaje')
                          small *
                        = f.input_field :mensaje, as: :text, class: 'required sm-form-control', required: true, rows: '6', cols: '30', maxlength: '400', id: 'mensaje' 
                    .col_full
                        = f.button :submit, t('contacto.enviar'), id: 'submit-button', class:'button button-3d nomargin', tabindex:"5" 
              
            .col_half.col_last
                section#google-map.gmap style="height: 410px;"
                = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBOMwzO67ohjT5ZdENZvRbvz_xiehstMO4&callback=initMap'
                
                javascript:
                  $(function() {
                    var map;
                    // Creando Latitud y longitud del mapa de Mendoza
                    var latlng = new google.maps.LatLng(-33.0242274, -68.7589029);

                    // Se establecen las corrdenadas del mapa
                    // Opciones del mapa 
                    var options = {
                        //     Centrando el mapa 
                        center: latlng,
                        zoom: 14,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };

                    // Creando el mapa referenciando el div
                    map = new google.maps.Map($('#google-map')[0], options);
                    
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(-33.0242274, -68.7589029),
                        map: map,
                        animation: google.maps.Animation.DROP
                    });
                    
                  });

            .clear
            .row.clear-bottommargin
                .col-md-3.col-sm-6.bottommargin.clearfix
                    .feature-box.fbox-center.fbox-bg.fbox-plain
                        .fbox-icon
                            a target="_blank" href="https://www.google.com.ar/maps/place/Vistandes/@-33.024256,-68.758978,15z/data=!4m2!3m1!1s0x0:0xd6bbd8c3d6f103bc?sa=X&ved=0ahUKEwi0--yh3LvMAhVDS5AKHTdEDFYQ_BIIfzAN" 
                              i.icon-map-marker2
                        h3 
                          = t('contacto.direccion')
                          span.subtitle Urquiza 5517, Maipú, Mendoza <br/> Argentina
                .col-md-3.col-sm-6.bottommargin.clearfix 
                    .feature-box.fbox-center.fbox-bg.fbox-plain
                        .fbox-icon
                            a href="#" 
                              i.icon-phone3
                        h3 
                          = t('contacto.telefonos')
                          span.subtitle +54 261 5246213  <br/> +54 261 5246214  <br/> +54 9 261 2189752 <br/>+54 9 261 4542847
                .col-md-3.col-sm-6.bottommargin.clearfix
                    .feature-box.fbox-center.fbox-bg.fbox-plain
                        .fbox-icon
                            a target="_blank" href="mailto:info@vistandes.com?Subject=Contacto"
                              i.icon-mail
                        h3 
                          = t('contacto.correos')
                          span.subtitle 
                            a target="_blank" href="mailto:info@vistandes.com?Subject=Contacto" info@vistandes.com 
                            a target="_blank" href="mailto:administracion@vistandes.com?Subject=Contacto" administracion@vistandes.com 
                .col-md-3.col-sm-6.bottommargin.clearfix
                    .feature-box.fbox-center.fbox-bg.fbox-plain
                        .fbox-icon
                            a target="_blank" href="https://www.facebook.com/Vistandes"
                              i.icon-facebook
                        h3 
                          = t('contacto.siguenos')
                          span.subtitle 
                            a target="_blank" href="https://www.facebook.com/Vistandes" facebook.com/Vistandes

app/views/static_pages/finca_single.html.slim
- provide(:current_page, 'finca_single')
- provide(:current_finca, @finca.name)
section#fincas.section_custom
  .container
    .title
      h3 = @finca.name
    div class="tab"
      .description.col-md-offset-1.col-md-10
        p = @finca.description
      .galeria.col_full.clearfix
        .masonry-thumbs.col-5 data-big="2" data-lightbox="gallery"
          - @finca.finca_imgs.each do |imgs|
            a href=imgs.image.url data-lightbox="gallery-item"
              = image_tag imgs.image(:medium), class: "image_fade"
    .end_quote
      blockquote
        p 
          i = t('fincas.descripcion')
    

app/views/static_pages/quienes_somos.html.slim
- provide(:current_page, t('quienes_somos.titulo'))
section#quienes.section_custom
  .container
    .title
      h3 = t('quienes_somos.titulo')
    
    .resume.col-md-8.col-md-offset-2
      p = t('quienes_somos.p1')
      p = t('quienes_somos.p2')
      p = t('quienes_somos.p3')
      p = t('quienes_somos.p4')
      p = t('quienes_somos.p5')